- src/domains/___stub.ts.njk
- src/http/nodegen/routes/___op.ts.njk
closes https://github.com/acrontum/openapi-nodegen-typescript-server/issues/5
Trim descriptions in nunjuks templates for routes and domains, removing the trailing newline that appears in doxy comments.
> opt-in description trimming

- src/http/nodegen/routes/___op.ts.njk
**Is your feature request related to a problem? Please describe.**
By default, the http routes will always generate 200's for success. This means the swagger definitions will disagree with the implementation
**Describe the solution you'd like**
If there is a single success (200-level) response defined in the yml for a route, then it would be cool it the generated files automatically extracted that
**Describe alternatives you've considered**
Manually changing the routes, which results in being overridden on re-generate
**Additional context**
will add `.status(<code>)` if there is only 1 200-level status code in path responses
depends on https://github.com/acrontum/generate-it/pull/22
> [FEATURE] add status code parser to routes

- package.json.njk
- src/http/middlewareErrorHandling.ts
Most of the 422's are handled by joi, but if we need to manually validate (eg something that cannot be expressed in the api spec) then throwing a 422 results in a 500
Current workaround:
```typescript
import http422 from '@/http/nodegen/errors/422';
...
if (some complicated condition) {
const error = http422(`I'm sorry Dave, I'm afraid I can't do that`);
error.joi = true;
throw error;
}
```
> fix: remove duplicate tslib from package.json, enable 422 error middleware

- src/http/nodegen/middleware/handle422.ts
Allow 
```typescript
throw http422('This is an informative error')
```
There may be a better way to do this for all errors, maybe something that checks if `error.message` is defined, and if it is an object or string:
```typescript
// errors/common.ts
export const ERR_MESSAGES = {
...
422: 'Unprocessable',
500: 'Oh noes!',
}
export const respondWithError = (error: Error, res: express.Response, code: number) => {
if (!error?.message) {
return res.status(code).send();
}
if (typeof error.message === 'string') {
return res.status(code).send(error.message || ERR_MESSAGES[code]);
} 
return res.status(code).json(error.message);
}
```
```typescript
// handle422.ts
if (err instanceof http422) {
return respondWithError(err, res, 422);
} else {
next(err);
}
```
> [FEATURE] add json message to 422

- src/http/nodegen/request-worker/WorkerService.ts
**Issue:**
When an error is sent from a worker thread to the main process we are getting an `http500()` with the following JSON response:
`{ message: '[object Object]' }`.
This occurs because the errors sent by the worker threads are not being properly unserialized.
**Fix:**
After this patch is applied we're now getting properly unserialized `error4*()` or `Error()` instances which are handled by their corresponding express.js middlewares.
> Unserialize worker thread errors to proper Error() instances.

- README.md
- src/http/nodegen/routes/___op.ts.njk
- src/http/nodegen/routesImporter.ts.njk
1. Proper handling of the OA3 JSON response in the route's handler. It was previously return an empty 200 response.
2. Allow for a user to specify basePath when calling the `routesImporter`, because OA3 basePath is part of the url and it's not taken care off by the `routeImporter` template.
example:
```typescript
import express from 'express';
import middlewareErrorHandling from './http/middlewareErrorHandling';
import middlewaresImporter from './http/middlewaresImporter';
import routesImporter from './http/nodegen/routesImporter';
const app = express();
middlewaresImporter(app);
routesImporter(app, '/v1');
middlewareErrorHandling(app);
export default app;
``
Defaults to an empty string when not specified
> OA3 fixes and accomodations

- .nodegenrc
Add nesting as a default option - it is much easier to turn this off than to later turn it on... i keep forgetting about this feature until i realise i need it
> Add the nested domains as a default option

- src/http/nodegen/request-worker/process.ts
- src/http/nodegen/request-worker/thread.ts
added worker error logs (likely way too verbose) and fixed error-spawn-error loop
workers were dying immediately (`Error: Cannot find module 'openapi-nodegen-logger'`), then just starting again forever, and never responding to requests.
In addition to fixing that particular error, added very verbose error and exit logging to at least show if this happens again
> fix: workers were restarting themselves in a loop

- githooks/pre-push
Trying to enforce more testing done locally - it's far too much to do it on pre-commit, so pre-push seems reasonable.
Added 755 mode to hooks (enable both by default if `dev:setup` is run).
> Replace pre-rebase with pre-push hook, which runs tests

- src/http/nodegen/interfaces/GenerateItExpressResponse.ts
- src/http/nodegen/middleware/inferResponseType.ts
- src/http/nodegen/utils/getPreferredResponseFormat.ts
Should resolve all use-cases of content negotiation.
With no accept header, `*/*` is assumed, and with no produces in the open api spec, `application/json` is assumed.
Knowing that, we can parse and prioritize the accept header and find which content-type in our possible return types matches those.
This does not validate the accept header or the produces values, so it's possible that invalid values could break the whole thing, but it appears to handle everything else
> Fix: content-negotiation

- docker-entrypoint.sh
We had the issue where migrations (run before npm start) were failing, but the app continued away, failing to start, dying, then rinse and repeat.
If any command fails in the startup script, it should immediately bail
> Exit on entrypoint error

- .eslintrc.js
default lint to ignore long functions in spec files
> ignore 40 line limit in spec files

- .nodegenrc
- package.json
Add default settings to object-reduce-by-map in nodegenrc
Assuming this goes through:
https://github.com/johndcarmichael/object-reduce-by-map/pull/12
> Add orbm nullish keys

- src/http/nodegen/tests/___eval.ts
nodegenrc params were not being parsed properly
these formats are accepted and properly parsed:
```json
{
"helpers": {
"tests": true
}
}
```
```json
{
"helpers": {
"tests": {
"outDir": "test/"
}
}
}
```
```json
{
"helpers": {
"tests": {
"outDir": "src/domains/spectacular"
}
}
}
```
> properly parse optional outDir param

- src/http/nodegen/tests/___eval.ts
Might break down with multiple possible success responses - but that would happen either way.
Hopefully adding an optional successCode will mitigate that - then if the user wants to test a specific code, that's on them.
> Tests should consider http 3xx as success

- src/http/nodegen/tests/___eval.ts
use async middleware by default - might mean extra `Promise.resolve` in places, but necessary in order to use async validation
> fix: allow async auth middleware

- src/domains/___stub.ts.njk
- src/http/nodegen/domainInterfaces/___op.ts.njk
There was some hard coded stuff in there still for the jwt token interface name
> gitflow-feature-stash: jwt-name-fix

- src/http/nodegen/tests/___eval.ts
async typing always returns "never", forcing any typing. Just allowing middleware seems to accept async middleware by default so will do that instead
> fix autogen types for mockauth helper

- package.json
update @types/express closes #174
> fix: express types conflict in celebrate latest

- Dockerfile
- add missing openapi yaml file to docker
- bump node version to latest lts
- setup multistage build, with runtime on alpine lts
closes #187
> fix: dockerfile fails to run if load_swagger_ui_route passed

- docker-compose.yml
make docker compose again
- remove unused build volume
- remove named network (this behaviour is default anyway - compose will spin up and name it's own network) and commented out external network example
> fix: dockerfile networking and cleanup

- README.md
- src/http/nodegen/routes/___op.ts.njk
https://github.com/sideway/joi/blob/master/API.md#anyvalidatevalue-options
ability to inject joi options on a path by path level
eg 
```
x-joi-options:
allowUnknown: true
```
or it looks like you can override the error message too, i think,  eg
```
x-joi-options:
messages:
email: <some translation key>
```
> joi-options-per-route

- README.md
- src/http/index.ts
- src/http/nodegen/middleware/applicationMiddleware.ts
**Problem:** Implementing healthcheck on K8s results in API logs being spammed by K8s/Docker pinging the healthcheck endpoint. Example log follows:
```log
api                | [api] ::ffff:127.0.0.1 [2023-06-16T10:53:57.748Z] "GET /health HTTP/1.1" 200 2 - 0.793 ms
api                | [api] ::ffff:127.0.0.1 [2023-06-16T10:54:07.818Z] "GET /health HTTP/1.1" 200 2 - 0.776 ms
api                | [api] ::ffff:127.0.0.1 [2023-06-16T10:54:17.899Z] "GET /health HTTP/1.1" 200 2 - 0.742 ms
api                | [api] ::ffff:127.0.0.1 [2023-06-16T10:54:28.001Z] "GET /health HTTP/1.1" 200 2 - 0.749 ms
api                | [api] ::ffff:127.0.0.1 [2023-06-16T10:54:38.109Z] "GET /health HTTP/1.1" 200 2 - 0.754 ms
```
**Solution:** Morgan logger already supports passing a custom (`skip(req: Request, …
> Enable passing of custom configuration for Access Logger middleware

- package-lock.json
- package.json
- audit fix for prod, dev deps still have warnings
- remove request-ip from packages, use a simpler pattern.
- the request-ip packages just checks a few extra headers, if we really expect those to show up we can just check for more headers in our own lib and save a few deps
> chore: deps. audit fixes and remove mostly unused lib

- src/cli/run.ts
- src/config.ts
- src/http/nodegen/tests/___eval.ts
- src/services/AccessTokenService.ts
- src/services/AsyncValidationService.ts
- src/services/CacheService.ts
- src/services/HttpHeadersCacheService.ts
- src/services/PermissionService.ts
If a project bumps their prettier version to v3, the template currently crashes.
Prettier v3 now returns a promise from the format call, so writeFileSync fails.
Wrapping the format in a Promise.resolve and .then ensures that projects on both prettier v2 and v3 can use this template.
WIP Because I'm not sure what the preferred way would be to handle errors here though. If for some reason there's an error with the formatting there will be an uncaught exception which might make for horrible logs.
Some possible options:
- Catching the errors and doing something (could be as simple as console.error and process.exit())
- Refactoring all this code to be async (and handle either async or sync prettier)
- Somehow force prettier to run synchronously
Open to suggestions which I can implement asap. …
> fix - support prettier v3 in templated projects

- Dockerfile
- docker-compose.yml
Update Dockerfile and docker-compose templates to only install prod dependencies on runtime and avoid using the root user.
> feat: Update Dockerfile and docker-compose.yml templates

- package.json
Add `dev:debug` script to support debugger with --inspect
This will make it easy to just attach your favorite debugger without a sweat
> Add `dev:debug` script to support debugger with --inspect

- src/http/nodegen/routes/___op.ts.njk
oa2 - nothing changed
oa3: fixed
when the schema looks like this:
```
responses:
'200':
description: OK
content:
audio/mpeg:
schema:
$ref: ../../components/schemas/question/ask/voice/model.yml
```
Instead of the routes file output this::
```
async (req: any, res: GenerateItExpressResponse) => {
res.inferResponseType(
await TextToVoiceDomain.textToVoicePost(req.body, req.jwtData),
200,
undefined,
textToVoiceTransformOutputs.textToVoicePost
);
}
```
it now pulls out the correct produces type (assumes the 1st) resulting in:
```
async (req: any, res: GenerateItExpressResponse) => {
res.inferResponseType(
await TextToVoiceDomain.textToVoicePost(req.body, req.jwtData),
200,
'audio/mpeg',
textToVoiceTransformOutputs.textToVoicePost
);
}
```
This means the output can be more than just json.. …
> fix: the oa3 was incorrectly leaving undefined in the outputs breaking the infer response middleware unless json

- .nodegenrc
- README.md
- src/domains/___stub.ts.njk
As the title says really.. 
When true in the rc config file, the tpl will not print the doc block in the domain file.
When the spec url segments are named well, there is little reason for the docblock
> noDomainDocBlock option for omitting the doc blocks in the domains

- README.md
- src/http/nodegen/middleware/applicationMiddleware.ts
- src/http/nodegen/routes/___op.ts.njk
If you require the express raw body add this to the respective path:
```
x-raw-body: true
```
This will result in no validation, no token checks, no body parsing, the domain will be provided the body in a raw format,
If you are handling webhooks from 3rd parties such as Stripe, you will need this flag set.
- https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express/main.ts#L34
For the `express.raw` to work it cannot be used in combination with `express.json({ limit: '50mb' }),`
As such, the `express.json({ limit: '50mb' }),` or `express.raw({ type: '*/*' }),` are now injected route by route depending on the existence of `x-raw-body: true` in the openapi path file.
Docs extended to accommodate new feature.
> feat: raw body
